Use bash directly

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -40,8 +40,20 @@ runs:
     - name: Install Kani
       shell: bash
       run: |
-        pwd
-        ./scripts/install-kani.sh ${{ inputs.kani-version }}
+        # If version is latest, install directly from cargo
+        if [ "$1" == "latest" ]; then
+            cargo install --locked kani-verifier;
+        else
+            VERSION=$1
+            cargo install --version $VERSION --locked kani-verifier;
+        fi
+        # Check exit status for error handling
+        if [ $? -ne O ]; then
+            echo "Error installing Kani. Please check if the provided version is correct"
+            exit 1
+        fi
+        # Setup kani in ci
+        cargo-kani setup;
 
     - name: Install PropProof
       if: ${{ inputs.enable-propproof == 'true' }}
